"""Add uploaded_by and url to Document

Revision ID: b359f85d20be
Revises: c38d9dd3eec9
Create Date: 2025-05-29 15:06:49.606717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b359f85d20be'
down_revision: Union[str, None] = 'c38d9dd3eec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'url')
    op.drop_column('documents', 'uploaded_by')
    # ### end Alembic commands ###
