"""Add assigned_reviewer_id to Document

Revision ID: fb40e09f0b7c
Revises: b359f85d20be
Create Date: 2025-05-29 15:49:53.103341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb40e09f0b7c'
down_revision: Union[str, None] = 'b359f85d20be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True))
        # Provide a name for the foreign key constraint for reliable dropping in downgrade
        batch_op.create_foreign_key('fk_documents_assigned_reviewer_id', 'users', ['assigned_reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        # Use the name of the foreign key constraint to drop it
        batch_op.drop_constraint('fk_documents_assigned_reviewer_id', type_='foreignkey')
        batch_op.drop_column('assigned_reviewer_id')
    # ### end Alembic commands ###
